# Styles management for QuartoDocBuilder.jl
# Provides CSS generation with optional default styles

# Path to bundled default CSS
const DEFAULT_CSS_PATH = joinpath(@__DIR__, "default_styles.css")

"""
    _base_styles() -> String

Read the default CSS styles from the bundled file.
Returns an empty string if the file is not found.
"""
function _base_styles()
    if isfile(DEFAULT_CSS_PATH)
        return read(DEFAULT_CSS_PATH, String)
    else
        # Fallback: return minimal CSS comment
        return "/* QuartoDocBuilder - No default styles found */\n"
    end
end

"""
    _should_apply_default_styles(theme::ThemeConfig) -> Bool

Determine whether default QuartoDocBuilder styles should be applied.

Returns `true` only when:
- `use_default_styles` is `true` (default)
- No bootswatch theme is specified (user wants default styles)
- No custom CSS is specified
- No custom SCSS is specified
"""
function _should_apply_default_styles(theme::ThemeConfig)::Bool
    # Don't apply if explicitly disabled
    if !theme.use_default_styles
        return false
    end

    # Don't apply if user specified custom CSS (they want full control)
    if !isempty(theme.custom_css)
        return false
    end

    # Don't apply if user specified custom SCSS
    if !isempty(theme.custom_scss)
        return false
    end

    # Don't apply if user specified ANY bootswatch theme
    # (even "flatly" - if explicitly set, user wants Quarto's theme system)
    if !isempty(theme.bootswatch)
        return false
    end

    return true
end

"""
    quarto_styles_from_config(config::QuartoConfig)

Generate CSS/SCSS files based on configuration.

Default styles are applied only when:
- No bootswatch theme is specified in ThemeConfig
- No custom CSS/SCSS is provided
- `use_default_styles` is true (default)

Creates:
- `docs/styles.css` - Main CSS file (with default or custom styles)
- `docs/custom.scss` - SCSS variables (if custom colors/fonts specified)

# Arguments
- `config::QuartoConfig`: Configuration with theme settings

# Examples
```julia
# Default (no theme) - applies default QuartoDocBuilder styles
config = QuartoConfig(module_name=MyModule, theme=ThemeConfig())
quarto_styles_from_config(config)

# With bootswatch theme - does NOT apply default styles
config = QuartoConfig(module_name=MyModule, theme=ThemeConfig(bootswatch="flatly"))
quarto_styles_from_config(config)

# Explicitly disable default styles
config = QuartoConfig(module_name=MyModule, theme=ThemeConfig(use_default_styles=false))
quarto_styles_from_config(config)
```
"""
function quarto_styles_from_config(config::QuartoConfig)
    theme = config.theme

    # Generate SCSS variables if custom colors/fonts specified
    has_custom_scss = !isempty(theme.primary) || !isempty(theme.bg) ||
                      !isempty(theme.fg) || !isempty(theme.accent) ||
                      !isempty(theme.font_base) || !isempty(theme.font_heading) ||
                      !isempty(theme.font_code) || !isempty(theme.custom_scss)

    if has_custom_scss
        scss = "// Custom theme variables generated by QuartoDocBuilder\n\n"

        !isempty(theme.primary) && (scss *= "\$primary: $(theme.primary);\n")
        !isempty(theme.bg) && (scss *= "\$body-bg: $(theme.bg);\n")
        !isempty(theme.fg) && (scss *= "\$body-color: $(theme.fg);\n")
        !isempty(theme.accent) && (scss *= "\$link-color: $(theme.accent);\n")
        !isempty(theme.font_base) && (scss *= "\$font-family-sans-serif: $(theme.font_base);\n")
        !isempty(theme.font_heading) && (scss *= "\$headings-font-family: $(theme.font_heading);\n")
        !isempty(theme.font_code) && (scss *= "\$font-family-monospace: $(theme.font_code);\n")

        if !isempty(theme.custom_scss)
            scss *= "\n// Custom SCSS\n$(theme.custom_scss)\n"
        end

        write("docs/custom.scss", scss)
        @info "Created docs/custom.scss with theme customizations"
    end

    # Determine if we should apply default styles
    should_apply_defaults = _should_apply_default_styles(theme)

    # Generate CSS
    if should_apply_defaults
        css = _base_styles()
    else
        css = "/* QuartoDocBuilder - Using Quarto theme: $(isempty(theme.bootswatch) ? "default" : theme.bootswatch) */\n"
    end

    # Add CSS for custom primary color (as CSS variables for runtime)
    if !isempty(theme.primary)
        css *= """

/* Custom primary color */
:root {
  --primary-color: $(theme.primary);
}

a {
  color: var(--primary-color);
}

.btn-primary {
  background-color: var(--primary-color);
  border-color: var(--primary-color);
}
"""
    end

    # Add custom CSS
    if !isempty(theme.custom_css)
        css *= "\n/* Custom CSS */\n$(theme.custom_css)\n"
    end

    write("docs/styles.css", css)
    if should_apply_defaults
        @info "Created docs/styles.css with default QuartoDocBuilder styles"
    else
        @info "Created docs/styles.css (minimal - using Quarto theme)"
    end
end
